defaults:
  - _self_
  - augmentations: asymmetric_gaussian_blur.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

gaussian_sigma: null

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "mocov3_gs224_t15_ggb1"
method: "mocov3"
backbone:
  name: "resnet50"
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 256
  pred_hidden_dim: 4096
  temperature: 0.1
momentum:
  base_tau: 0.996
  final_tau: 0.996
data:
  dataset: ego4d
  train_path: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/shared/datasets/Ego4d/h5"
  val_path: None
  format: "h5"
  num_workers: 8
  dataset_kwargs:
    gaze_size: 224
    time_window: 15
    center_crop: False #To compare gaze crop with a center crop with gaze size 540
    resize_gs: False  # resize gaze to 224 before applying transform
optimizer:
  name: "lars"
  batch_size: 64
  lr: 1.6
  classifier_lr: 3e-3
  weight_decay: 1e-6
  no_labels: True
scheduler:
  name: "warmup_cosine"
  warmup_epochs: 0.01
checkpoint:
  enabled: True
  dir: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/schaumloeffel/logs/ego4d/"
  frequency: 1
  keep_prev: True
  every_n_iter: 5000
auto_resume:
  enabled: False
wandb:
  enabled: True
  entity: "aaubret"
  project: "EgocentricVision"
  group: "mocov3-rn50"
  job_type: "train"

knn_clb:
  enabled: True
  dataset: imagenet100_42
  train_path: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/shared/datasets"
  val_path: "/pfss/mlde/workspaces/mlde_wsp_PI_Roig/shared/datasets/"
  num_workers: 8
  batch_size: 64
  k: [10, 20, 50, 100]
  perform_on_validation: False
  perform_every_n_batches: 0.1 # perform every 10% of the training batches
  verbose: True
  transform_kwargs:
    global_gaussian_blur:
      sigma: ${gaussian_sigma}

# overwrite PL stuff
max_epochs: 1
devices: 8
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 32
no_validation: True
limit_val_batches: 0
num_sanity_val_steps: 0
val_check_interval: 5000
log_every_n_steps: 50