defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "simclr-nymeria"
method: "simclr"
backbone:
  name: "resnet50"
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 128
  temperature: 0.1
data:
  dataset: nymeria
  train_path: "/scratch_shared/aubret/nymeria/"
  val_path: None
  format: "h5"
  num_workers: 8
  dataset_kwargs:
    gaze_size: 224
    time_window: 3
    center_crop: False #To compar e gaze crop with a center crop with gaze size 540
    resolution: 512
    fps: 1
optimizer:
  name: "lars"
  batch_size: 128
  lr: 1.6
  classifier_lr: 3e-3
  weight_decay: 1e-6
  no_labels: True
scheduler:
  name: "warmup_cosine"
  warmup_epochs: 5
checkpoint:
  enabled: True
  dir: "trained_models2"
  frequency: 1
  keep_prev: False
  save_last: True
auto_resume:
  enabled: True

knn_clb:
  enabled: True
  verbose: True
  dataset: imagenet_42
  k:
    - 10
    - 20
    - 50
    - 100
  perform_on_validation: True
  val_path: /home/aubret/
  train_path: /home/aubret/
  format: h5
  freq_epochs: 5

# overwrite PL stuff
max_epochs: 50
devices: 4
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed
no_validation: True
limit_val_batches: 0
num_sanity_val_steps: 0
log_every_n_steps: 50