defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "pascalvoc_mocov3"

backbone:
  name: "vit_base"
method: "mocov3"
data:
  dataset: PascalVOC
  train_path: "/scratch_shared/aubret/pascalvoc"
  val_path: "/scratch_shared/aubret/pascalvoc"
  num_workers: 4
  augmentations:
    img_size: 224
optimizer:
  name: "sgd"
  batch_size: 64
  lr: 0.1
  weight_decay: 0
scheduler:
  name: "step"
  lr_decay_steps: [60, 80]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
  keep_prev: False
  save_last: True
auto_resume:
  enabled: False
early_stopping:
  enabled: False

grid:
  enabled: False
  lr: [0.1,0.2,0.4,0.8]
  use_avgpool: [ False ]
  use_cls_token: [ False ]
  use_n_blocks: [ 1 ]
use_projector: True
pre_extract_feats: False
finetune: False

# overwrite PL stuff
max_epochs: 100
devices: 4
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 32
log_every_n_steps: 50
